version: "3"
services:
  nginx:
    ports:
      - "8080:80"

  node-app:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=jillian
      - MONGO_PASSWORD=password
      - SESSION_SECRET=secret
    command: npm run dev

  mongo:
    image: amd64/mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jillian
      - MONGO_INITDB_ROOT_PASSWORD=password
 
